name: Generate File List

on:
  push:
    branches:
      - main
    paths:
      - 'business/cdn/file/**'
  workflow_dispatch:

jobs:
  generate-file-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file-list.json
        run: |
          ls business/cdn/file | jq -R -s -c 'split("\n")[:-1]' > business/cdn/file-list.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add business/cdn/file-list.json
          git commit -m "Update file list" || exit 0
          git push
